column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "None"
trailing_comma = "None"
format_on_save = true
license_template = "None"
newline_style = "Unix"
ignore = []
```
