#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restar action="sudo yabai --load-sa"


# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.60
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  3
yabai -m config bottom_padding               5
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# space labels
yabai -m space 1 --label DEV
yabai -m space 2 --label OwO
yabai -m space 3 --label Stream
yabai -m space 4 --label Edition
yabai -m space 5 --label Messages
yabai -m space 6 --label secondary1
yabai -m space 7 --label secondary2
yabai -m space 8 --label secondary3
yabai -m space 9 --label secondary4
yabai -m space 10 --label secondary5

# window rules
yabai -m rule --add app="^Arc$" space=2
yabai -m rule --add app="^Warp$" space=1
yabai -m rule --add app="^IINA$" space=3
yabai -m rule --add app="^chatterino$" space=3
yabai -m rule --add app="^Obsidian$" space=4
yabai -m rule --add app="^Telegram$" space=5
yabai -m rule --add app="^Discord$" space=5
yabai -m rule --add app="^Mail$" space=5
yabai -m rule --add app="^Messages$" space=5

# ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
