#!/usr/bin/env sh

sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.60
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 7
yabai -m config right_padding                7
yabai -m config window_gap                   8

# space labels
yabai -m space 1 --label DEV
yabai -m space 2 --label OwO
yabai -m space 3 --label video
yabai -m space 4 --label Notes
yabai -m space 5 --label Messages
yabai -m space 6 --label Email
yabai -m space 7 --label Remote
yabai -m space 8 --label Docs
yabai -m space 9 --label VM
yabai -m space 10 --label Trash

# ignore apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Perplexity$" manage=off

echo "yabai configuration loaded.."
